In [2]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)

#### *Student Score Checker*

In [ ]:
mat = np.random.randint(1,100,(12,5))
print(mat)

In [ ]:
first_row = mat[:,3]
print(np.mean(mat, axis = 1))  # row wise mean
print(np.mean(mat, axis = 0))  # col wise mean

In [ ]:
print(mat[1,:])
print(mat[:,0])
print(mat[1:,0])
print(mat[5,2:])
print(mat[len(mat)-1, 1:len(mat[0])-1])
print(len(mat[0]))
print(mat[1:len(mat)-1, 1:len(mat[0])-1])

### *complete blood count analyzer*

In [ ]:
# hemoglobin range 12 - 15
# rbc count 4m - 6m 
# wbc count 4.5k - 11k
# platelet count 150k - 450k
# hematocrit range 35.5% - 50%
# mcv range 80 - 100
# mch range 27 - 33
# mchc range 32% - 36%

In [ ]:
sex = np.random.randint(0,2,(10,1))
age = np.random.randint(10,61, (10,1))
heme = np.random.randint(1,25,(10,1))
rbc = np.random.randint(1,10, (10,1))
wbc = np.random.randint(1,20, (10,1))
plat = np.random.randint(10,900, (10,1))
hcrit = np.random.randint(1,100,(10,1))
mcv = np.random.randint(50,130, (10,1))
mch = np.random.randint(10,50,(10,1))
mchc = np.random.randint(30,41,(10,1))

In [16]:
data = np.hstack((sex,age,heme,rbc,wbc,plat,hcrit,mcv,mch,mchc))
print(data)

[[  1  55  14   7   4 781  76  80  32  31]
 [  0  47  15   6   2 839  25  52  30  39]
 [  0  22   8   8   4  69  67  55  48  32]
 [  0  30  16   5  10 540  39  93  10  39]
 [  0  23   3   4  19 357  53  70  37  33]
 [  1  33   7   9   6 516  68 114  32  39]
 [  1  48  18   8  11 188  56  96  28  37]
 [  1  21   6   3  15 333  84 116  26  30]
 [  1  58  20   7   7 329   8  66  47  35]
 [  1  57  15   7   9 565   9 110  21  30]]


[[1 2 3]
 [4 5 6]]


In [ ]:
# hackerrank concatenate in numpy
import numpy as np
n,m,p = map(int,input().split())

lst1 = []
for i in range(n):
    lst1.append(list(map(int, input().split())))
arr1 = np.array(lst1)

lst2 = []
for i in range(m):
    lst2.append(list(map(int, input().split())))
arr2 = np.array(lst2)
print(np.concatenate((arr1,arr2), axis = 0))

In [ ]:
# when input length is varying
value = list(map(int,input().split()))
print(np.zeros(tuple(value),dtype=int))
print(np.ones(tuple(value),dtype=int))

3
3
0


array([], shape=(3, 3, 0), dtype=int64)

In [46]:
x,y = list(map(int,input().split()))
print(x,y)

2 5


3

array([1, 2, 3])